import { VALIDITY, POINT_FEATURE } from "$lib/enum"

export const VALIDITY_DISTANCE = new Map([
  [POINT_FEATURE.CHECKPOINT, { [VALIDITY.VALID]: 0.01, [VALIDITY.WARN]: 0.08 }],
  [POINT_FEATURE.SUMMIT, { [VALIDITY.VALID]: 0.008, [VALIDITY.WARN]: 0.05 }],
  [POINT_FEATURE.WATER_ENTRY, { [VALIDITY.VALID]: 0.2, [VALIDITY.WARN]: 0.3 }],
  [POINT_FEATURE.WATER_EXIT, { [VALIDITY.VALID]: 0.2, [VALIDITY.WARN]:  0.3 }],
  [POINT_FEATURE.WATER_CHECKPOINT, { [VALIDITY.VALID]: 0.045, [VALIDITY.WARN]:  0.1 }],
])